const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const out=process.argv[2];fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto(process.env.COMFY_URL||'http://127.0.0.1:8207/');await page.waitForFunction(()=>window.app?.daelabMaterialGroups);await page.waitForTimeout(1500);await page.keyboard.press('Escape');
await page.evaluate(async()=>{await app.loadGraphData({nodes:[],links:[],groups:[],extra:{}});app.daelabCreativeCanvas.show();const cards=app.graph.extra.daelabCreativeCanvasV1.cards;window.testIds=[];for(let i=0;i<4;i++){const n=LiteGraph.createNode('DAELAB.MediaUpload');app.graph.add(n);n.title='场景素材 '+(i+1);n.widgets.find(w=>w.name==='asset_data').value=JSON.stringify({version:1,id:'fixture-'+i,kind:'image',name:'山景长文件名用于检查溢出和圆角.png',filename:'mountain.png',subfolder:'DAELAB/group-review-demo'});cards[n.id]={x:40+i%2*370,y:100+Math.floor(i/2)*350,width:350,expanded:true};testIds.push(n.id);}app.daelabCreativeCanvas.sync();});
await page.waitForTimeout(700);
const card=id=>page.locator(`.dae-creative-card[data-node-id="${id}"]`);const ids=await page.evaluate(()=>testIds);
await card(ids[0]).locator('strong').first().dblclick();await page.getByLabel('节点名称',{exact:true}).fill('双击重命名素材');await page.keyboard.press('Enter');assert.equal(await card(ids[0]).locator('strong').first().textContent(),'双击重命名素材');
await card(ids[0]).locator('.dae-upload-stage').click();await card(ids[1]).locator('.dae-upload-stage').click({modifiers:['Shift']});await page.getByRole('button',{name:'素材打组',exact:true}).click();await page.waitForTimeout(600);
assert.equal(await page.locator('[data-review-group=true]').count(),1);
const firstGroup=page.locator('[data-review-group=true]').first();await firstGroup.locator('strong').first().dblclick();await page.getByLabel('节点名称',{exact:true}).fill('双击重命名组');await page.keyboard.press('Enter');assert.equal(await firstGroup.locator('strong').first().textContent(),'双击重命名组');
await page.evaluate(()=>app.daelabCreativeCanvas.select(null));await card(ids[0]).locator('.dae-upload-stage').hover();await page.waitForTimeout(200);assert.equal(await card(ids[0]).getAttribute('data-slots-suppressed'),'true');
await card(ids[0]).locator('.dae-upload-stage').click();await page.waitForTimeout(200);assert.equal(await card(ids[0]).getAttribute('data-slots-suppressed'),'false');assert.equal(await firstGroup.getAttribute('data-slots-suppressed'),'true');assert.equal(await firstGroup.locator('.dae-creative-ports').evaluate(e=>getComputedStyle(e).visibility),'hidden');
await page.screenshot({path:path.join(out,'member-slot-selected.png')});await page.evaluate(()=>app.daelabCreativeCanvas.select(null));await page.waitForTimeout(200);assert.equal(await firstGroup.getAttribute('data-slots-suppressed'),'false');console.log('PASS title double click and mutually exclusive member slots');

await card(ids[2]).locator('.dae-upload-stage').click();await card(ids[3]).locator('.dae-upload-stage').click({modifiers:['Shift']});await page.keyboard.press('Control+g');await page.waitForTimeout(600);assert.equal(await page.locator('[data-review-group=true]').count(),2);
assert.equal(await page.getByText('载入示例工作流',{exact:true}).count(),0);assert.equal(await page.evaluate(()=>String(app.queuePrompt).includes('execution disabled')),false);
await page.getByRole('button',{name:'蓝色',exact:true}).click();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup').filter(g=>g.properties.reviewColor==='#b8c4ff').length),1);
const prompt=await page.evaluate(()=>app.graphToPrompt());const groups=Object.values(prompt.output).filter(n=>n.class_type==='DAELAB.MaterialGroup');assert.equal(groups.length,2);assert.equal(JSON.parse(groups[0].inputs.collection_data).assets.length,2);
await page.evaluate(()=>app.daelabCreativeCanvas.root.focus());await page.keyboard.press('Control+z');await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup').filter(g=>g.properties.reviewColor==='#b8c4ff').length),0);
await page.keyboard.press('Control+Shift+z');await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup').filter(g=>g.properties.reviewColor==='#b8c4ff').length),1);
console.log('PASS native undo/redo and executable collection');
await page.evaluate(()=>app.daelabCreativeCanvas.select(app.graph._nodes.find(n=>n.type==='DAELAB.MaterialGroup')));await page.waitForTimeout(250);
await page.getByRole('button',{name:'宫格排列 ▾',exact:true}).click();await page.getByRole('button',{name:'垂直排列',exact:true}).click();await page.waitForTimeout(350);
await page.getByRole('button',{name:'组选项 ▾',exact:true}).click();await page.getByRole('button',{name:'收起组',exact:true}).click();await page.waitForTimeout(200);assert.equal(await page.locator('[data-review-member]:visible').count(),2);
await page.getByRole('button',{name:'组选项 ▾',exact:true}).click();await page.getByRole('button',{name:'展开组',exact:true}).click();
await page.getByRole('button',{name:'组选项 ▾',exact:true}).click();await page.getByRole('button',{name:'锁定组',exact:true}).click();await page.getByRole('button',{name:'垂直排列 ▾',exact:true}).click();assert.ok(await page.getByRole('button',{name:'水平排列',exact:true}).isDisabled());await page.keyboard.press('Escape');
await page.getByRole('button',{name:'组选项 ▾',exact:true}).click();await page.getByRole('button',{name:'解锁组',exact:true}).click();
await page.getByLabel('自定义组颜色',{exact:true}).fill('#447788');await page.waitForTimeout(400);assert.equal(await page.getByRole('button',{name:'自定义颜色 #447788',exact:true}).count(),1);
await page.getByRole('button',{name:'序号',exact:true}).click();assert.equal(await page.evaluate(()=>app.graph._nodes.find(n=>n.type==='DAELAB.MaterialGroup').properties.showNumbers),false);
console.log('PASS layout, collapse/expand, lock, custom color and numbers');

// Exercise the actual DOM clipboard handlers (the payload goes through native core copy/paste).
await page.evaluate(()=>{const g=app.graph._nodes.find(n=>n.type==='DAELAB.MaterialGroup');app.daelabCreativeCanvas.select(g);const data=new DataTransfer();app.daelabCreativeCanvas.root.dispatchEvent(new ClipboardEvent('copy',{bubbles:true,clipboardData:data}));app.daelabCreativeCanvas.root.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,clipboardData:data}));});await page.waitForTimeout(700);
assert.equal(await page.evaluate(()=>app.graph._nodes.length),9);assert.equal(await page.evaluate(()=>new Set(app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup').flatMap(g=>g.properties.members)).size),6);
await page.getByRole('button',{name:'删除组',exact:true}).click();await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>app.graph._nodes.length),6);
await page.evaluate(()=>app.daelabCreativeCanvas.root.focus());await page.keyboard.press('Control+z');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>app.graph._nodes.length),9);
console.log('PASS copy remaps members; delete and undo retain whole group');
await page.evaluate(()=>{const v=app.graph.extra.daelabCreativeCanvasV1;v.viewport={x:90,y:100,zoom:.7};app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup').forEach((g,i)=>(Object.assign(v.cards[g.id],{x:(i%2)*800,y:Math.floor(i/2)*700}),g.properties.fixtureLayout=1));app.daelabCreativeCanvas.show();});await page.waitForTimeout(400);
const gid=await firstGroup.getAttribute('data-node-id');const start=await page.evaluate(id=>app.graph.extra.daelabCreativeCanvasV1.cards[id].x,gid);const header=await firstGroup.locator('.dae-creative-heading').boundingBox();await page.mouse.move(header.x+80,header.y+20);await page.mouse.down();await page.mouse.move(header.x+120,header.y+50,{steps:8});await page.mouse.up();await page.waitForTimeout(250);assert.ok(await page.evaluate(({id,x})=>app.graph.extra.daelabCreativeCanvasV1.cards[id].x>x+30,{id:gid,x:start}));
await page.evaluate(()=>app.daelabCreativeCanvas.root.focus());await page.keyboard.press('Control+z');await page.waitForTimeout(450);assert.ok(Math.abs(await page.evaluate(id=>app.graph.extra.daelabCreativeCanvasV1.cards[id].x,gid)-start)<1);
const firstMember=page.locator(`[data-review-member="${gid}"]`).first();await firstMember.locator('.dae-upload-stage').click();await page.waitForTimeout(300);const memberHeader=await firstMember.locator('.dae-upload-stage').boundingBox();const targetBounds=await page.locator('[data-review-group=true]').nth(1).boundingBox();await page.mouse.move(memberHeader.x+90,memberHeader.y+12);await page.mouse.down();await page.mouse.move(targetBounds.x+100,targetBounds.y+targetBounds.height-15,{steps:12});await page.mouse.up();await page.waitForTimeout(400);assert.equal(await page.evaluate(id=>app.graph.getNodeById(id).properties.members.length,gid),1);
await page.evaluate(()=>app.daelabCreativeCanvas.root.focus());await page.keyboard.press('Control+z');await page.waitForTimeout(400);assert.equal(await page.evaluate(id=>app.graph.getNodeById(id).properties.members.length,gid),2);
console.log('PASS group move and member transfer with native undo');

await page.evaluate(()=>{app.daelabCreativeCanvas.hide();if(document.querySelector('.gr-metadata-clip'))throw new Error('Leaked media overlay after hide');app.daelabCreativeCanvas.show();});await page.waitForTimeout(600);
const saved=await page.evaluate(()=>app.graph.serialize());fs.writeFileSync(path.join(out,'workflow.json'),JSON.stringify(saved,null,2));await page.reload();await page.waitForFunction(()=>window.app?.daelabMaterialGroups);await page.evaluate(async data=>{await app.loadGraphData(data);app.daelabCreativeCanvas.show();},saved);await page.waitForTimeout(1000);assert.equal(await page.locator('[data-review-group=true]').count(),3);
await page.evaluate(()=>{app.daelabCreativeCanvas.fit();const g=app.graph._nodes.find(n=>n.type==='DAELAB.MaterialGroup');app.daelabCreativeCanvas.select(g);});await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'production.png')});
for(const zoom of [.3,1,2]){await page.evaluate(z=>{app.graph.extra.daelabCreativeCanvasV1.viewport={x:70,y:80,zoom:z};app.daelabCreativeCanvas.show();const g=app.graph._nodes.find(n=>n.type==='DAELAB.MaterialGroup');app.daelabCreativeCanvas.select(app.graph.getNodeById(g.properties.members[0]));},zoom);await page.waitForTimeout(450);await page.screenshot({path:path.join(out,`zoom-${zoom}.png`)});const buttons=page.locator('[data-selected=true] .gr-media-action:visible');assert.equal(await buttons.count(),zoom===.3?0:3);if(zoom>=1){const dimensions=await buttons.evaluateAll(list=>list.map(e=>{const r=e.getBoundingClientRect();return [r.width,r.height,getComputedStyle(e).borderRadius]}));for(const [w,h,r] of dimensions){assert.ok(Math.abs(w-h)<.1);assert.equal(r,'50%');}}}

await page.evaluate(()=>{const groups=app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup');const cards=app.graph.extra.daelabCreativeCanvasV1.cards;groups.forEach((g,i)=>{cards[g.id].x=i*780;cards[g.id].y=70;});const target=groups[1];target.addInput('test collection consumer','DAELAB_ASSETS');groups[0].connect(0,target,target.inputs.length-1);app.daelabCreativeCanvas.show();app.daelabCreativeCanvas.select(groups[0]);app.daelabCreativeCanvas.fit();});await page.waitForTimeout(500);assert.equal(await page.locator('.gr-wire-pulse').count(),1);const offset=await page.locator('.gr-wire-pulse').evaluate(e=>getComputedStyle(e).strokeDashoffset);await page.waitForTimeout(180);assert.notEqual(await page.locator('.gr-wire-pulse').evaluate(e=>getComputedStyle(e).strokeDashoffset),offset);
await page.evaluate(()=>{app.graph.extra.daelabCreativeCanvasV1.viewport.zoom*=.8;app.daelabCreativeCanvas.show();});await page.waitForTimeout(200);assert.ok(await page.locator('.gr-wire-pulse').evaluate(e=>parseFloat(e.style.animationDelay)<-.1));await page.screenshot({path:path.join(out,'pulse.png')});
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(250);assert.equal(await page.locator('.gr-wire-pulse').evaluate(e=>getComputedStyle(e).animationName),'none');
await page.evaluate(()=>{const g=app.graph._nodes.filter(n=>n.type==='DAELAB.MaterialGroup')[1];g.removeInput(g.inputs.length-1);});
await page.evaluate(()=>app.daelabCreativeCanvas.select(app.graph._nodes.find(n=>n.type==='DAELAB.MaterialGroup')));await page.waitForTimeout(250);const count=await page.evaluate(()=>app.graph._nodes.length);await page.getByRole('button',{name:'组选项 ▾',exact:true}).click();await page.getByRole('button',{name:'解散组',exact:true}).click();await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>app.graph._nodes.length),count-1);
console.log('PASS pulse phase, reduced motion and dissolve preserves members');

await page.evaluate(async()=>{await app.loadGraphData({nodes:[],links:[],groups:[],extra:{}});app.daelabCreativeCanvas.show();for(const [i,width] of [350,680].entries()){const n=LiteGraph.createNode('DAELAB.MediaUpload');app.graph.add(n);app.graph.extra.daelabCreativeCanvasV1.cards[n.id]={x:40+i*430,y:180,width,expanded:true};}app.daelabCreativeCanvas.sync();});await page.waitForTimeout(500);
for(const z of [.5,1,1.4]){await page.evaluate(z=>{app.graph.extra.daelabCreativeCanvasV1.viewport={x:40,y:50,zoom:z};app.daelabCreativeCanvas.show();},z);await page.waitForTimeout(200);for(const ratio of await page.locator('.dae-upload-stage').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return r.width/r.height})))assert.ok(Math.abs(ratio-16/9)<.01);}
await page.evaluate(()=>{app.graph.extra.daelabCreativeCanvasV1.viewport.zoom=1;app.daelabCreativeCanvas.show();});await page.waitForTimeout(200);const empty=page.locator('.dae-upload-stage').first(),r=await empty.boundingBox(),before=await page.evaluate(()=>Object.values(app.graph.extra.daelabCreativeCanvasV1.cards)[0].x);await page.mouse.move(r.x+80,r.y+80);await page.mouse.down();await page.mouse.move(r.x+150,r.y+110,{steps:10});await page.mouse.up();assert.ok(await page.evaluate(x=>Object.values(app.graph.extra.daelabCreativeCanvasV1.cards)[0].x>x+50,before));await page.waitForTimeout(250);await page.screenshot({path:path.join(out,'empty-16-9.png')});assert.equal(await page.getByText('每个上传节点承载一份素材，请一次选择一个文件',{exact:true}).count(),0);console.log('PASS two empty sizes at three zooms, body drag and no obsolete hint');

await page.evaluate(()=>{for(const n of app.graph._nodes)n.widgets.find(w=>w.name==='asset_data').value=JSON.stringify({version:1,id:String(n.id),kind:'image',name:'16比10素材.png',filename:'mountain.png',subfolder:'DAELAB/group-review-demo'});app.daelabCreativeCanvas.sync();});await page.waitForFunction(()=>[...document.querySelectorAll('.dae-upload-stage img')].length===2&&[...document.querySelectorAll('.dae-upload-stage img')].every(i=>i.naturalWidth>0));
for(const z of [.5,1,1.4]){await page.evaluate(z=>{app.graph.extra.daelabCreativeCanvasV1.viewport={x:40,y:50,zoom:z};app.daelabCreativeCanvas.show();},z);await page.waitForTimeout(250);for(const m of await page.locator('.dae-upload-stage img').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),s=e.parentElement.getBoundingClientRect();return {ratio:r.width/r.height,natural:e.naturalWidth/e.naturalHeight,gap:s.width-r.width,heightGap:s.height-r.height};}))){assert.ok(Math.abs(m.ratio-m.natural)<.005);assert.ok(m.gap<4&&m.heightGap<4);}}
await page.evaluate(()=>{app.graph.extra.daelabCreativeCanvasV1.viewport.zoom=1;app.daelabCreativeCanvas.show();});await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'loaded-natural-ratio.png')});console.log('PASS loaded media fills two widths at natural ratio through zoom');
assert.deepEqual(errors,[]);console.log('PASS normal URL, 2 instances, modes, serialized reload, zoom and round actions');
}catch(e){await page.screenshot({path:path.join(out,'failure.png')});console.log('ERRORS',errors);throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
