const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
    const out=path.resolve(process.argv[2]||'artifacts/video-edit/interaction');fs.mkdirSync(out,{recursive:true});
    const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1800,height:1300}});
    page.setDefaultTimeout(18000);const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
    try{
        await page.goto(process.env.COMFY_URL||'http://127.0.0.1:8209');await page.waitForFunction(()=>window.app?.daelabMaterialGroups&&LiteGraph.registered_node_types['DAELAB.VideoEdit']);await page.waitForTimeout(1600);await page.keyboard.press('Escape');
        const ids=await page.evaluate(async()=>{
            await app.loadGraphData({nodes:[],links:[],groups:[],extra:{}});app.daelabCreativeCanvas.show();const cards=app.graph.extra.daelabCreativeCanvasV1.cards,uploads=[];
            for(const [i,name] of ['red.png','motion.mp4','blue.png'].entries()){const n=LiteGraph.createNode('DAELAB.MediaUpload');app.graph.add(n);n.widgets.find(w=>w.name==='asset_data').value=JSON.stringify({version:1,id:'asset-'+i,kind:i===1?'video':'image',filename:name,subfolder:'',name});cards[n.id]={x:30,y:50,width:350,expanded:true};uploads.push(n.id);}
            const group=LiteGraph.createNode('DAELAB.MaterialGroup');app.graph.add(group);group.title='混合素材组';group.properties.members=uploads;cards[group.id]={x:25,y:30,width:730,expanded:false};
            const edit=LiteGraph.createNode('DAELAB.VideoEdit');app.graph.add(edit);cards[edit.id]={x:800,y:30,width:840,expanded:true};app.graph.extra.daelabCreativeCanvasV1.viewport={x:35,y:35,zoom:.85};app.daelabCreativeCanvas.show();return {group:group.id,edit:edit.id,uploads};
        });
        const group=page.locator(`.dae-creative-card[data-node-id="${ids.group}"]`),card=page.locator(`.dae-creative-card[data-node-id="${ids.edit}"]`),panel=card.locator('.dae-edit');
        await panel.waitFor({state:'visible'});await page.waitForTimeout(500);
        async function connectFrom(source){
            await source.locator('.dae-creative-heading').hover();
            const port=source.locator('button[data-side=output]').first(),a=await port.boundingBox(),b=await card.locator('.dae-creative-heading').boundingBox();
            await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+180,b.y+b.height/2,{steps:15});await page.mouse.up();
        }
        await connectFrom(group);
        await page.waitForFunction(id=>JSON.parse(app.graph.getNodeById(id).widgets.find(w=>w.name==='edit_data').value).clips.length===3,ids.edit);
        let clips=()=>page.evaluate(id=>JSON.parse(app.graph.getNodeById(id).widgets.find(w=>w.name==='edit_data').value).clips,ids.edit);
        assert.deepEqual((await clips()).map(c=>c.asset.name),['red.png','motion.mp4','blue.png']);
        console.log('PASS group connection automatically imports ordered mixed media');
        const edge=panel.locator('.dae-edit-clip').first().getByRole('button',{name:'调整片段终点'}),edgeBox=await edge.boundingBox();
        await page.mouse.move(edgeBox.x+edgeBox.width/2,edgeBox.y+40);await page.mouse.down();await page.mouse.move(edgeBox.x+edgeBox.width/2+54.4,edgeBox.y+40,{steps:8});await page.mouse.up();
        assert.ok(Math.abs((await clips())[0].duration-4)<.03);
        await panel.focus();await page.keyboard.press('Control+z');
        await page.waitForFunction(id=>Math.abs(JSON.parse(app.graph.getNodeById(id)?.widgets.find(w=>w.name==='edit_data').value||'{"clips":[]}').clips[0]?.duration-3)<.03,ids.edit);
        await page.waitForFunction(()=>!app.configuringGraph);
        await panel.focus();await page.keyboard.press('Control+Shift+z');
        await page.waitForFunction(id=>Math.abs(JSON.parse(app.graph.getNodeById(id)?.widgets.find(w=>w.name==='edit_data').value||'{"clips":[]}').clips[0]?.duration-4)<.03,ids.edit);
        const last=await panel.locator('.dae-edit-clip').last().boundingBox(),first=await panel.locator('.dae-edit-clip').first().boundingBox();
        await page.mouse.move(last.x+30,last.y+30);await page.mouse.down();await page.mouse.move(first.x+14,first.y+30,{steps:10});await page.mouse.up();assert.equal((await clips())[0].asset.name,'blue.png');
        const ruler=await panel.locator('.dae-edit-ruler').boundingBox();await page.mouse.click(ruler.x+54.4,ruler.y+10);await panel.getByRole('button',{name:'分割',exact:true}).click();assert.equal((await clips()).length,4);
        console.log('PASS real edge drag, native undo/redo, reorder and playhead split');
        await panel.getByLabel('预览',{exact:true}).selectOption('1');
        await page.mouse.click(ruler.x+1,ruler.y+10);await panel.getByRole('button',{name:'播放',exact:true}).click();await page.waitForTimeout(3600);
        assert.ok((await panel.getByLabel('播放时间',{exact:true}).textContent()).startsWith('00:03'));
        assert.equal(await panel.locator('.dae-edit-stage img').isVisible(),true);
        await panel.getByRole('button',{name:'暂停',exact:true}).click();
        await page.mouse.click(ruler.x+6.8*54.4,ruler.y+10);await panel.getByRole('button',{name:'播放',exact:true}).click();await page.waitForTimeout(1100);await panel.getByRole('button',{name:'暂停',exact:true}).click();
        assert.equal(await panel.locator('.dae-edit-stage video').isVisible(),true);
        const sync=await panel.evaluate(e=>({source:e.querySelector('.dae-edit-stage video').currentTime,clock:e.querySelector('.dae-edit-position').textContent}));
        const seconds=Number(sync.clock.split(' / ')[0].split(':')[1]);assert.ok(Math.abs(seconds-(7+sync.source))<0.06);
        console.log('PASS continuous image-to-video playback and source clock synchronisation');
        await page.screenshot({path:path.join(out,'group-timeline.png')});
        await card.getByRole('button',{name:'展开编辑器',exact:true}).click();
        const dialog=page.locator('.dae-creative-workspace');await dialog.waitFor({state:'visible'});
        assert.equal(await dialog.locator('.dae-edit').count(),1);await page.screenshot({path:path.join(out,'workspace.png')});
        await dialog.getByRole('button',{name:'返回画布',exact:true}).click();
        const edited=await clips();
        await page.evaluate(id=>app.graph.getNodeById(id).properties.members.reverse(),ids.group);await page.waitForTimeout(800);
        assert.deepEqual(await clips(),edited);
        await panel.getByRole('button',{name:'导出视频',exact:true}).click();await panel.locator('.dae-edit-result a').waitFor({state:'visible',timeout:60000});
        console.log('PASS expanded workspace and typed connected-group export after source group reorder');
        await panel.getByRole('button',{name:'导出视频',exact:true}).waitFor({state:'visible'});
        await page.waitForFunction(id=>!app.graph.getNodeById(id).__videoEdit.root.querySelector('[data-primary]').disabled,ids.edit);
        await page.evaluate(id=>{const n=app.graph.getNodeById(id),widget=n.widgets.find(w=>w.name==='edit_data'),data=JSON.parse(widget.value);data.clips[0].duration=300;widget.value=JSON.stringify(data);n.__videoEdit.reload();},ids.edit);
        await panel.getByRole('button',{name:'导出视频',exact:true}).click();await panel.getByRole('button',{name:'取消导出',exact:true}).waitFor({state:'visible'});await panel.getByRole('button',{name:'取消导出',exact:true}).click();await page.waitForTimeout(500);
        assert.match(await panel.locator('.dae-edit-status').textContent(),/取消/);
        console.log('PASS targeted cancellation of this edit export');
        const slider=panel.getByRole('slider',{name:'时间轴缩放'});await slider.fill('80');
        const view=panel.locator('.dae-edit-scroll'),viewBox=await view.boundingBox();
        const head=await panel.locator('.dae-edit-head').boundingBox();await page.mouse.move(head.x+head.width/2,head.y+8);await page.mouse.down();await page.mouse.move(viewBox.x+viewBox.width-3,head.y+8,{steps:15});await page.waitForTimeout(900);
        const right=await view.evaluate(e=>e.scrollLeft);assert.ok(right>100);
        const rightTime=await panel.getByLabel('当前预览时间',{exact:true}).textContent();
        await page.mouse.move(viewBox.x+3,head.y+8,{steps:15});await page.waitForTimeout(650);const left=await view.evaluate(e=>e.scrollLeft);assert.ok(left<right);
        assert.notEqual(await panel.getByLabel('当前预览时间',{exact:true}).textContent(),rightTime);await page.mouse.up();
        const stopped=await view.evaluate(e=>e.scrollLeft);await page.waitForTimeout(250);assert.equal(await view.evaluate(e=>e.scrollLeft),stopped);
        const beforeZoom=Number(await slider.inputValue());await panel.getByRole('button',{name:'缩小时间轴'}).click();assert.ok(Number(await slider.inputValue())<beforeZoom);await panel.getByRole('button',{name:'放大时间轴'}).click();
        await page.screenshot({path:path.join(out,'scrub-slider.png')});
        console.log('PASS draggable playhead scrolls both directions, stops on release, and slider/buttons stay synchronized');
        await page.evaluate(id=>{const n=app.graph.getNodeById(id);n.disconnectInput(n.inputs.findIndex(i=>i.name==='assets'));},ids.edit);
        await page.waitForFunction(id=>JSON.parse(app.graph.getNodeById(id).widgets.find(w=>w.name==='edit_data').value).clips.length===0,ids.edit);
        await page.evaluate(({group,edit})=>{const n=app.graph.getNodeById(edit);app.graph.getNodeById(group).connect(0,n,n.inputs.findIndex(i=>i.name==='assets'));},ids);
        await page.waitForFunction(id=>JSON.parse(app.graph.getNodeById(id).widgets.find(w=>w.name==='edit_data').value).clips.length===3,ids.edit);
        console.log('PASS disconnect removes linked clips and reconnect imports once');
        await page.evaluate(id=>{const n=app.graph.getNodeById(id);n.disconnectInput(n.inputs.findIndex(i=>i.name==='assets'));},ids.edit);
        await page.waitForFunction(id=>JSON.parse(app.graph.getNodeById(id).widgets.find(w=>w.name==='edit_data').value).clips.length===0,ids.edit);
        const upload=await page.evaluate(({group})=>{app.graph.extra.daelabCreativeCanvasV1.cards[group].y=1800;const n=LiteGraph.createNode('DAELAB.MediaUpload');app.graph.add(n);n.widgets.find(w=>w.name==='asset_data').value=JSON.stringify({version:1,id:'single',kind:'image',filename:'red.png',subfolder:'',name:'red.png'});app.graph.extra.daelabCreativeCanvasV1.cards[n.id]={x:30,y:30,width:400,expanded:true};app.daelabCreativeCanvas.sync();return n.id;},ids);
        await page.waitForTimeout(500);await connectFrom(page.locator(`.dae-creative-card[data-node-id="${upload}"]`));
        await page.waitForFunction(id=>JSON.parse(app.graph.getNodeById(id).widgets.find(w=>w.name==='edit_data').value).clips.length===1,ids.edit);
        assert.match((await clips())[0].source.slot,/images/);
        const previousResult=await panel.locator('.dae-edit-result a').getAttribute('href');
        await panel.getByRole('button',{name:'导出视频',exact:true}).click();
        await page.waitForFunction(({id,previous})=>{const link=app.graph.getNodeById(id).__videoEdit.root.querySelector('.dae-edit-result a');return link&&link.getAttribute('href')!==previous;},{id:ids.edit,previous:previousResult},{timeout:60000});
        console.log('PASS real single-image socket connection and typed export');
        assert.deepEqual(errors,[]);
    }catch(error){await page.screenshot({path:path.join(out,'failure.png')});console.error('PAGE ERRORS',errors);throw error;}
    finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
